"""Add accessible_pages

Revision ID: 7b325f2deceb
Revises: 20260922_no_push
Create Date: 2026-10-01 11:04:28.546156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b325f2deceb'
down_revision = '20260922_no_push'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accessible_pages', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('accessible_pages')

    # ### end Alembic commands ###
